FROM python:3.12

LABEL maintainer="muneebxhasan@gmail.com"

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    protobuf-compiler \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code

RUN pip install poetry

COPY . /code/

RUN poetry config virtualenvs.create false

EXPOSE 8089

RUN poetry install

CMD [ "poetry","run","uvicorn","app.main:app","--host","0.0.0.0","--port","8089","--reload" ]
